# SPDX-FileCopyrightText: 2024 Winni Neessen <wn@neessen.dev>
#
# SPDX-License-Identifier: CC0-1.0

name: Codecov workflow
on:
  push:
    branches:
      - main
    paths:
      - '**.go'
      - 'go.*'
      - '.forgejo/**'
      - 'codecov.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**.go'
      - 'go.*'
      - '.forgejo/**'
      - 'codecov.yml'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@master
    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    - name: Run Tests
      run: |
        go test -v -shuffle=on -race --coverprofile=coverage.coverprofile --covermode=atomic ./...
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
